### ISSUE TITLE
Chrome 71: Clicking on a link(Set to open in new tab/window) in fullscreen window will exit fullscreen and return to default size.

### ISSUE THREAD

**Issue by nav311** [sindresorhus/screenfull.js#115]

**Comment by nav311** [comment]
But IE and older version of chrome are working as expected..link opens in a new window/tab based on browser settings without exiting full-screen.

**Comment by photonstorm** [comment]
Try it for yourself just using a standard `requestFullscreen()` JavaScript call. There's nothing in the screenfull code that specifically prevents this, which implies it's a change in the way Chrome works and outside your control I'd suspect.

**Comment by photonstorm** [comment]
Anything that removes focus from the full screen element is going to do that.

**Comment by adripanico** [comment]
> Even if I try to view source by right clicking, will exit full screen mode.

That isn't happening to me.
