### ISSUE TITLE
Integration with Angular 6

### ISSUE THREAD

**Issue by HashimJaved09** [sindresorhus/screenfull.js#116]
I have installed package using:
***npm install screenfull***
included the ***cdnjs*** link in ***index.html*** file of my project
used ***<button toggleFullscreen>Toggle fullscreen<button>*** in html file
nothing happens.
Also tried adding ***"node_modules/screenfull/dist/screenfull.js"*** in the ***angular.json*** file
nothing happens when I click above button!

**Comment by sindresorhus** [comment]
Try https://github.com/hrajchert/angular-screenfull instead.

For additional support, try Angular support forums instead.

**Comment by HashimJaved09** [comment]
@sindresorhus if we have a long page and after toggling to full screen there is no way scroll down!
can this be resolved!
