### ISSUE TITLE
Page Scroll not working in Chrome 71.0.3

### ISSUE THREAD

**Issue by adnanrafique** [sindresorhus/screenfull.js#119]
I've checked the #29 and #58 Already. But nothing did solved this issue.

Reproduce:

1. Open the demo page
2. go to full screen by clicking on the toggle button (or any other button that takes you there)
3. Try to scroll the page with your finger - not working

I am using windows 10 and Chrome version 71.0.3
Also checked on Firefox 64. Still nothing

**Comment by sindresorhus** [comment]
This package package is just a compatibility wrapper for the native fullscreen API. If scrolling is not working, it's either the native fullscreen API that is at fault or you using it incorrectly.

**Comment by adnanrafique** [comment]
Thank you for your response. I'm not even using it. I just checked the demo and I opened this as this is happening in the demo.
