### ISSUE TITLE
Uncaught (in promise) TypeError: Document not active

### ISSUE THREAD

**Issue by Hariss096** [sindresorhus/screenfull.js#120]
The error is coming when the app is first launched. The problem is on line 102:

`document[fn.exitFullscreen]();`

I fixed this issue by catching the error thrown by the promise like this : 

`document[fn.exitFullscreen]().catch(() => {});`

Would love to have this solution officially.

For reference, I am using version 3.3.3. I also updated to the latest version which is at the moment v4.0.0 but the error is still there.

**Comment by kepner03** [comment]
I faced the same issue with Chrome 72.

There was an other solution in https://github.com/jpilfold/ngx-image-viewer/issues/23
what has worked for me too.
  
1. Go to the file : ~src/node_modules/screenfull/dist/screenfull.js . 
2. find around line 100 the exit function . 
3.replace with the following :  
```
exit: function () {
   if (this.isFullscreen) {
	document[fn.exitFullscreen]();
  }
},
```

**Comment by sunnibfgi** [comment]
fix solution:
document.exitFullscreen().catch(err => Promise.resolve(err))
