### ISSUE TITLE
ScreenFull doesn't work on firefox 66.0 version

### ISSUE THREAD

**Issue by lukaonik** [sindresorhus/screenfull.js#128]
I am trying to use screenfull.js for toggling fullscreen on firefox, it doesn;t work, if i use
```
   var docElm = document.documentElement;

    docElm.mozRequestFullScreen();

```
it works

**Comment by sindresorhus** [comment]
The example in https://sindresorhus.com/screenfull.js/ works fine for me in Firefox 66.

**Comment by lukaonik** [comment]
It doesn't work if y are trying to fullscreen from iframe

**Comment by sindresorhus** [comment]
From the docs:

> If your page is inside an <iframe> you will need to add a allowfullscreen attribute (+ webkitallowfullscreen and mozallowfullscreen).

**Comment by lukaonik** [comment]
It worked thanxs
