### ISSUE TITLE
Issue with system sounds on Safari 12

### ISSUE THREAD

**Issue by vavgustov** [sindresorhus/screenfull.js#129]
1. open https://sindresorhus.com/screenfull.js/
2. unfocus textfield (click anywhere on document)
3. try to click any buttons on keyboard => no sounds
4. enter full screen and try to click any buttons on keyboard => system sounds

**Comment by sindresorhus** [comment]
This is just a wrapper for the native Fullscreen API. Issues like these are issues in the browser and should be reported on the Safari issue tracker.
