### ISSUE TITLE
[enhancement] Please add screenfull.min.js to npm

### ISSUE THREAD

**Issue by ffaubert** [sindresorhus/screenfull.js#132]
It would be very helpful if you could please add screenfull.min.js to npm.  My application uses many front end libraries and screenfull is the only one that does not publish the minified version to npm.  

Adding this would help my usecase tremendously and should not impact anyone else's usage of the library.

Thank you for considering it.

**Comment by sindresorhus** [comment]
I'm not interested in that. You can get a minified version at https://unpkg.com or https://www.jsdelivr.com
