### ISSUE TITLE
Jest test not passing (On and Off)

### ISSUE THREAD

**Issue by cristiancs** [sindresorhus/screenfull.js#136]
I have the following code

    componentDidMount() {
		screenfull.on("change", this.changeIcon);
	}
	componentWillUnmount() {
		screenfull.off("change", this.changeIcon);
	}`

But when running a simple test

    it("Barra inferior renders without crashing", () => {
	const div = document.createElement("div");
	ReactDOM.render(
		<BarraInferior title="Testing" canonical="XX" />,
		div
	);
	ReactDOM.unmountComponentAtNode(div);
    });
I get this error

`
 Barra inferior renders without crashing

    TypeError: _screenfull.default.on is not a function

      34 |      }
      35 |      componentDidMount() {
    > 36 |              screenfull.on("change", this.changeIcon);
         |                         ^
      37 |      }
      38 |      componentWillUnmount() {
      39 |              screenfull.off("change", this.changeIcon);

`

**Comment by sindresorhus** [comment]
Seems to be a problem with your setup for transpilation. Screenfull works fine normally, so it's not something wrong with Screenfull.
