### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by dingetje** [sindresorhus/screenfull.js#137]
Hi, I'm using your screenfull script, works great in most browsers, but shows a SCRIPT1002 syntax error in IE11 on Windows 10 clients:

```javascript
// add handler for Full Screen change detected
  if (screenfull.enabled) {
      // IE11 shows syntax error on next line
      screenfull.on('change', () => {
        console.log('Am I fullscreen?', screenfull.isFullscreen ? 'Yes' : 'No');
        $('#fullscreentoggle').prop('checked', screenfull.isFullscreen);
      });
    }
```
![image](https://user-images.githubusercontent.com/609871/57508115-efb01780-7300-11e9-8fc9-58fe17ee47b7.png)

**Comment by sindresorhus** [comment]
IE11 doesn't support arrow functions; You're using arrow functions in the above code.

**Comment by dingetje** [comment]
You're absolutely right, rewrote to function calls.
