### ISSUE TITLE
Invalid 'reference' directive syntax

### ISSUE THREAD

**Issue by 704826318** [sindresorhus/screenfull.js#138]
ERROR in node_modules/screenfull/dist/screenfull.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax

**Comment by m00dy** [comment]
How did you fix this ?

**Comment by jigneshkapdiya** [comment]
Just Open screenfull.d.ts and save it, Its solve my issue. 
or replace /// <reference lib="dom"/> with // <reference lib="dom"/>

![image](https://user-images.githubusercontent.com/8413866/65403976-2c823400-ddf4-11e9-89e8-edcf4cb9e3ec.png)

**Comment by Ferhatos** [comment]
Hello,
Is it possible to fix this issue in lib code please ?
We use this fix  in an auto build chain (Nexus & Jenkins for example)

**Comment by chandrasekharu** [comment]
Hi @sindresorhus no body want's to fix this in node_modules. It's not the right way to fix the issue in library. It's open source and all team members can't change library code. what if the code builds through CI/CD pipeline

**Comment by sindresorhus** [comment]
There's nothing wrong with Screenfull. You need to upgrade your TypeScript version. See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499783519
