### ISSUE TITLE
'this' reference is undefined

### ISSUE THREAD

**Issue by GeorgeKnap** [sindresorhus/screenfull.js#141]
I am using screenfull.js 4.2.0 in Angular app and I'm curious if anyone encountered my situation as I'm running out of ideas.

this is how I use this library in one of my component:
```
import * as screenfull from 'screenfull';
import { Screenfull } from 'screenfull';

const sf = screenfull as Screenfull;
 if (sf.enabled) {
      sf.toggle(someElement);
    }
```

Everything works fine when it's served for development via `ng serve`.
However, when built via `ng build --prod` I'm getting runtime error ` TypeError: Cannot read property 'isFullscreen' of undefined`.
![Capture](https://user-images.githubusercontent.com/11920691/59185750-80347e80-8b71-11e9-948b-973f942bd8d1.PNG)

**Comment by 1615450788** [comment]
4.0.1 is normal

**Comment by sindresorhus** [comment]
Screenfull is an object, and its methods are not individual exports, so when you try to import each method individually with `import * as screenfull from 'screenfull';`, you lose the `this` binding. The correct way to import it is `import screenfull = require('screenfull');`.
