### ISSUE TITLE
Document that screenfull can be false

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [sindresorhus/screenfull.js#142]
Trying to use the new types has made me aware of this fact. It seems that wherever you use screenfull, you should actually wrap the block in a `if (screenfull)`.

Or of course use `if (screenfull && screenfull.enabled)`.
Which might also clear up [this confusion](https://github.com/sindresorhus/screenfull.js/issues/126).

Or... if a browser doesn't support full screen at all, don't return `false` but instead `{enabled: false}`.

**Comment by sindresorhus** [comment]
> Or... if a browser doesn't support full screen at all, don't return false but instead {enabled: false}.

Yeah, that would be nicer.
