### ISSUE TITLE
how to remove ECS to exit fullscreen

### ISSUE THREAD

**Issue by serenaFV** [sindresorhus/screenfull.js#143]
I want to remove the ESC  function which can exit fullscreen

**Comment by sindresorhus** [comment]
That's not possible. It's the browser that enforces the ability to Esc to exit.

**Comment by lzj666888** [comment]
use navigator.keyboard.lock(['escape'])

**Comment by lzj666888** [comment]
> That's not possible. It's the browser that enforces the ability to Esc to exit.

use navigator.keyboard.lock(['escape'])
