### ISSUE TITLE
fullscreen not working on iOS chrome 75

### ISSUE THREAD

**Issue by krist-jin** [sindresorhus/screenfull.js#146]
Given the supportability in https://caniuse.com/#feat=fullscreen the fullscreen API should work on Chome 75 in iOS, if I understand correctly.

However, looks like I'm not able to enter full screen mode using my iPhone even on https://sindresorhus.com/screenfull.js/ 

So is it not supported in iOS at all?

tested on iOS 12.3.1 Chrome 75.0.3770.103
Thanks!

**Comment by S2057** [comment]
Im also facing same issue

**Comment by kalitine** [comment]
No, it doesn't work on iPhone, only iPad. See Note 5 on https://caniuse.com/#feat=fullscreen 

> Partial support refers to supporting only iPad, not iPhone. Shows an overlay button which can not be disabled.
