### ISSUE TITLE
Docs: could we clarify iphone/safari support

### ISSUE THREAD

**Issue by AoDev** [sindresorhus/screenfull.js#152]
Hello, 

In the readme there are sentences like:

```
// Actually it's more if you want it to work in Safari, but let's not go there...
```
and

```
iPhone is not supported.
```

This is a bit cryptic to me because it's the first time I have to do something related to fullscreen and I don't have the full picture in mind, to understand the meaning of these. (I just know that Apple is a big pain in the *** for many things related to Safari)

From the first sentence, does it mean that "we can" or "we can not" make it work in safari? Does screenful.js work with Safari? (all versions?) 

For `iPhone is not supported`: iPhone is a device, so my question is: that's the whole Apple iOS system that is not supported or just Safari on an iPhone, or any browser in an iPhone?

**Comment by sindresorhus** [comment]
I've clarified it in the readme: https://github.com/sindresorhus/screenfull.js#support

**Comment by sindresorhus** [comment]
> or any browser in an iPhone?

While there are other browsers on iPhone, they all use the same rendering engine, WebKit, and so have the same limitations regarding APIs.

**Comment by AoDev** [comment]
@sindresorhus Thank you for the update, the answer and your full on this package :)

**Comment by mustafaekim** [comment]
The readme states that the library works in IPAD but it does not. Where should I look at?

**Comment by justingolden21** [comment]
Just found out my website crashes on all iPhones due to Screenful; is there a plan to support IOS in the future?
