### ISSUE TITLE
screenfull.on and .off is not a function

### ISSUE THREAD

**Issue by PeterKey** [sindresorhus/screenfull.js#153]
I am getting an error on iOS that screenfull.on is not a function. On every other platform it works as intended. I am using React in Webkit environment. Does anybody else have this problem? It's specific to mobile iOS. Is this maybe related to #139?

```javascript
componentDidMount () {
    screenfull.on('change', () => {
      this.setState({
        isFullscreen: screenfull.isFullscreen
      })
    })
  }
```

Cheers!

**Comment by sindresorhus** [comment]
You have to check `screenfull.enabled` before using it.

**Comment by PeterKey** [comment]
Thank you very much! This was it. I only checked for screenfull.enabled later on in the code.
