### ISSUE TITLE
Reload of page does not keep status

### ISSUE THREAD

**Issue by Martinomagnifico** [sindresorhus/screenfull.js#156]
Using Safari and the demo, I found that reloading the page (the whole document) while in fullscreen, the status will say that fullscreen is false. Chrome will revert to windowed mode, but Safari will stay fullscreen and report that it isn't. This is probably a Safari thing but I'm not sure.

**Comment by sindresorhus** [comment]
Yes, this is the behavior of the native implementation. Screenfull is only a more user-friendly layer on top.

**Comment by Martinomagnifico** [comment]
Thanks!!! I use screenfull in a plugin for Reveal.js and just noticed the behaviour. (You are credited in the JS :-) )
