### ISSUE TITLE
Import assignment cannot be used when targeting ECMAScript modules

### ISSUE THREAD

**Issue by GeorgeKnap** [sindresorhus/screenfull.js#161]
I'm using screenfull.js in typescript project targeting ES2015.

After updating to v 5.0.0 I should make a change in import statement 

`You need to change import screenfull from 'screenfull'; to import screenfull = require('screenfull');`

vscode mark this import with following error:
```
Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

**Comment by sindresorhus** [comment]
I cannot document all the possible config you can use with TS. The instructions are for default TS. Try to Google the error.

**Comment by GeorgeKnap** [comment]
what is the _default TS_ ?

**Comment by cdeutsch** [comment]
`import screenfull from 'screenfull';` still works but the only property that exists is `isEnabled`.

All of the functions are missing like `.request`, `.exit`, etc

If I keep `import screenfull from 'screenfull';`, and the following still works:
```
(screenfull as any).request()
```

That means Typescript is importing the actual code correctly but the typings are wrong.

I've yet to see someone recommend `import screenfull = require('screenfull');` in any scenario, so not really sure what that is attempting to get around.

Generally in typescript you'd use `const screenfull = require('screenfull')` to import a module that doesn't have typings.

**Comment by tmtron** [comment]
here is what I do after updating to version 5:

```typescript
import screenfull, { Screenfull } from 'screenfull';

const fullScreen = (screenfull.isEnabled) ? screenfull as Screenfull : undefined;
```
So my constant `fullScreen` is either the correctly typed `Screenfull` or `undefined`:  
now the use in typescript code is simple and intuitive, e.g.
```typescript
if (fullScreen) {
  fullScreen.toggle();
  ..
}
```
