### ISSUE TITLE
ScreenFull not working in iOS Chrome

### ISSUE THREAD

**Issue by adnanrafique** [sindresorhus/screenfull.js#164]
Whenever I try to open my application in fullscreen it shows following error in console.

`TypeError: undefined is not an object (evaluating 'screenfull__WEBPACK_IMPORTED_MODULE_23__["raw"].fullscreenchange')`

Now I know it does not work with safari on iPhone but It should work on Chrome and I am testing it in chrome. 

In the following condition,

`if (screenfull.enabled) {} => console.log(screenfull) => true  //it should return an object` This is the line  where it is getting failed.

**Comment by sindresorhus** [comment]
I think this is a problem with your Webpack config and not this package.

It works fine without Webpack: https://github.com/sindresorhus/screenfull.js/blob/38eeb420efaf0011e423fe761be18b0052c900c5/index.html#L158

**Comment by adnanrafique** [comment]
Any Idea how I can resolve this?

**Comment by Beraliv** [comment]
> Any Idea how I can resolve this?

Can you show your example?

**Comment by VincentCharpentier** [comment]
This is not really a bug, more like a bad feature from Apple.
The fullscreen API works on iPad but not on iPhone (http://caniuse.com/#feat=fullscreen)

> there is no way to switch to fullscreen on IOS >=10 in Safari and Chrome. It is because the Fullscreen API is not supported
> https://stackoverflow.com/a/46544156/3484498

Why ?
IMHO, Apple isn't thrilled by PWA and try to limit their adoption. Thus forcing devs to release apps on their marketplace which translate into big $ for them

**Comment by kevindecapite** [comment]
The demo on the homepage does not work on iPad (iOS 13.3.1) with Chrome 80.0.3987.95.

**Comment by shubhamcompro** [comment]
@adnanrafique is it working on IOS safari(iphone) for you?

**Comment by iamjoeker** [comment]
I'm seeing the same thing. On latest iPadOS, the demo:
1. Works in Safari
1. Does not work in Chrome
1. Does not work in FireFox

**Comment by hubery3721** [comment]
Is any solution?

**Comment by mustafaekim** [comment]
When I visit the [demo page](https://sindresorhus.com/screenfull.js/), I see that it does not work for both Safari and Chrome on an IPAD, 7th generation, IOS 13.5.1

Any idea why it does not work on IPAD? [Here](https://caniuse.com/#feat=fullscreen) it says that fullscreen API is supported on IPAD

**Comment by Shaker-Hamdi** [comment]
I'm having this issue, any solution yet?

**Comment by mustafaekim** [comment]
@Shaker-Hamdi what I've found out are as below

- if you click a click on - say a google doc, the link is opened inside the google doc shell. Even though it uses Safari, fullscreen does not work. However if you visit the same link by copying and pasting into the safari browser, it works!
- second thing to check is to ensure that you are requesting the desktop site

**Comment by Shaker-Hamdi** [comment]
@mustafaekim I'm not sure I follow, I'm only looking to trigger fullscreen on an element on the page, and it works in Safari iPad, but not Chrome for some reason.

**Comment by kkgo2018** [comment]
if (/ Version\/5\.1(?:\.\d+)? Safari\//.test(navigator.userAgent)) {
				elem[request]();
			} else {
        if (keyboardAllowed) {
                elem[request](Element.ALLOW_KEYBOARD_INPUT);
              } else {
                elem[request]({ navigationUI: "auto" });
              }
				// elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);
			}

**Comment by kofifus** [comment]
@kkgo2018 is that a fix ? where does this go and what does it do please ?

**Comment by droid95** [comment]
Same issue here, is not working on Iphone safari 14 and chrome 86.0.4240.93.

**Comment by CaelanStewart** [comment]
Same issue here - still isn't working.

**Comment by PaTiToMaSteR** [comment]
player.webkitEnterFullscreen();

**Comment by Richienb** [comment]
@sindresorhus screenfull.js only works in Safari on iPad:

![iPad Pro 12.9 2020 running iOS 14.0 on Browserstack](https://user-images.githubusercontent.com/29491356/104117408-f28cc680-5385-11eb-861f-e8bd3dcba198.jpg)

It does not work on Chrome or Safari on iPhone and Chrome on iPad.

This is because these browsers [don't support fullscreen mode](https://stackoverflow.com/a/46544156/8384910). We should add a link to the [caniuse](https://caniuse.com/fullscreen) page for the Full Screen API in the readme.

**Comment by sindresorhus** [comment]
There already is: https://github.com/sindresorhus/screenfull.js#support

I personally think it's already pretty clear, but PR welcome if you think it can be made clearer.

**Comment by nick-w-m** [comment]
Hey! Looking for clarification about this issue. Does no support mean `isEnabled` will be set to `false` on iOS, or does it mean the imported code will error out and not initialize successfully?

**Comment by Richienb** [comment]
`.isEnabled` appears to be `false`:

![Screenshot of the screenfull.js demo showing that isEnabled is false](https://user-images.githubusercontent.com/29491356/138259880-b8a4ada9-bc09-427e-a528-d863d1a23f37.png)

**Comment by khenriksson** [comment]
I had the same problem with `screenfull.isEnabled` not working in Safari on iPad. The only workaround was to use `controls={true}` to get the native "fullscreen" button visible.
