### ISSUE TITLE
Property 'exit' does not exist on type 'Screenfull | { isEnabled: false; }'

### ISSUE THREAD

**Issue by chandrasekharu** [sindresorhus/screenfull.js#165]
Hi I am in the process of upgrading my angular application from 5 to 8 

facing a error where it says **Property 'exit' does not exist on type 'Screenfull**

I want to toggle 'summary-fullscreen' element section only here 

I got two errors actually after upgrade. 

1) In showfullscreen function I used to have _screenfull.enabled_ I renamed it to _screenfull.isEnabled_ the error went off later I got the issue with property **exit** in closeFullscreen() funtion

showFullScreen() {
    const goFullScreenTarget = document.getElementById('summary-fullscreen');
    if (**screenfull.isEnabled**) {
      screenfull.request(goFullScreenTarget);
    }
  }
  closeFullScreen() {
    screenfull.**exit**();
  }

another issue, Property 'on' does not exist on type 'Screenfull

screenfull.**on**('change', () => {
      this.isFullscreen = !this.isFullscreen;
    });

**Comment by chandrasekharu** [comment]
@sindresorhus How can you close the issue without giving solution to this. it's still showing the error as  where it says **Property 'exit' does not exist on type 'Screenfull** please explain the fix

**Comment by sindresorhus** [comment]
@chandrasekharu "closed this in f0a14a3". It was fixed.
