### ISSUE TITLE
Returning native promise 

### ISSUE THREAD

**Issue by stormtrooper1859** [sindresorhus/screenfull.js#167]
Latest version of Chrome blocked information about fullscreen activation if it's happened in iframe and 'fullscreenchange' event won't fired. [Link from SO](https://stackoverflow.com/questions/21103478/fullscreenchange-event-not-firing-in-chrome). So promise, which returned from 'exit' function doesn't resolve. 
But document.exitFullscreen() returns native promise, which normally resolves.
What do you think about it?

You can repeat it by using youtube embedded video and calling functions from console.
I repeated it with Chrome 79 on macOS 10.14

**Comment by sindresorhus** [comment]
We still have to support the old way, but there could be a check to see if `document.exitFullscreen()` returns a promise and then use that directly instead of the events.
