### ISSUE TITLE
Typings only expose isEnabled (v5.0.2)

### ISSUE THREAD

**Issue by oisinlavery** [sindresorhus/screenfull.js#172]
<img width="757" alt="Screen Shot 2020-04-29 at 10 02 44 AM" src="https://user-images.githubusercontent.com/1757344/80578694-c9e3bd00-8a00-11ea-89ae-5d40b92b48a9.png">

Should I be casting the type myself?

**Comment by sindresorhus** [comment]
The rest of the properties are conditioned on an if-statement. See the docs and read the type definition file.
