### ISSUE TITLE
Need review: Add support for Safari mobile

### ISSUE THREAD

**Issue by bahung1221** [sindresorhus/screenfull.js#175]
Hi there,

I want to create an PR to add support for safari mobile (iPhone). I successful request fullscreen for video element on my company project (that work perfect for iPhone), so now I want to add this feature to `screenfull.js`.

Following this webkit API document: [WebKit JS HTMLVideoElement](https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1633500-webkitenterfullscreen).

But I faced a problem, `screenfull.js` stick all method (except `request` method) to `document element` while all API of `Webkit HTMLVideoElement` above only work on `video element` not the document.

Synonymous we must refactor current structure of project, i did it for all methods in my [fork repo](https://github.com/bahung1221/screenfull.js/commit/3e59a00f3fdc4c0e70d0add5be126a0a76e09a63), but i don't know what is better way for refactor instance properties (`isFullscreen`, `element`, `isEnabled`) that only check on `document element`

So please help to review my commit and give me some advise about it, thank you very much,
Happy Coding!

[My Commit](https://github.com/bahung1221/screenfull.js/commit/3e59a00f3fdc4c0e70d0add5be126a0a76e09a63)

**Comment by sindresorhus** [comment]
I'm unfortunately not interested in adding support for the WebKit video element fullscreen thing. It's too different from the rest and this package is done feature-wise.
