### ISSUE TITLE
New upcoming issue via chrome beta and unstable?

### ISSUE THREAD

**Issue by davidmaxwaterman** [sindresorhus/screenfull.js#176]
I often use the beta of chrome to develop on, and I've noticed a problem that seems to be affecting invoking full screen mode. I know it's a beta (or worse), but I thought I'd mention it since it's been getting 'closer and closer' over the past few months, and I'm worried it'll just hit 'stable' and my app will break.

It looks like the layout changes to be some kind of 'zoomed landscape' mode. IE, all the text get bigger, and it only covers the central half of the screen - like a margin-top: 25%, margin-bottom: 25%....though if I do a screenshot (using the dev tools' feature), while the screenshot is the correct dimensions/etc, it shows that middle 50% at the top of the screenshot (I see it's not quite 50% tall since it doesn't reach half way down).

If I reload, or move the window to another screen, then it seems to correct itself. The fact that it corrects itself when I simply move the browser window to another screen, makes me confident it is a chrome bug, but I figured I'd mention it, just in case.

It still behaves as expected on 'stable'.

Any thoughts?

Google Chrome	84.0.4147.30 (Official Build) beta (64-bit)
Revision	48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}
OS	Linux

**Comment by sindresorhus** [comment]
Screenfull.js just wraps the native APIs. It's not responsible for actually making the document/element fullscreen. There's nothing Screenfull.js can do about this.
