### ISSUE TITLE
Detect when I press F11 in Chrome

### ISSUE THREAD

**Issue by mugnap** [sindresorhus/screenfull.js#177]
Hello, I've find an issue with screenfull: even in your sample (https://sindresorhus.com/screenfull.js/) when I press F11 on Chrome (Windows) to go in Full Screen mode, you don't detect that we're in full screen (you still write "Is fullscreen: false"). How can I detect when F11 is pressed to enter (or exit) the full screen mode? 
Thanks

**Comment by sindresorhus** [comment]
Duplicate of #26
