### ISSUE TITLE
Chrome71版本使用screenfull.js全屏功能时报参数错误

### ISSUE THREAD

**Issue by kkgo2018** [sindresorhus/screenfull.js#180]
Chrome71版本使用screenfull.js全屏功能时报参数错误Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object

**Comment by kkgo2018** [comment]
if (/ Version\/5\.1(?:\.\d+)? Safari\//.test(navigator.userAgent)) {
				elem[request]();
			} else {
        if (keyboardAllowed) {
                elem[request](Element.ALLOW_KEYBOARD_INPUT);
              } else {
                elem[request]({ navigationUI: "auto" });
              }
				// elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);
			}

**Comment by sindresorhus** [comment]
You're not using the latest Screenfull version.
