### ISSUE TITLE
5.0以后的在chrome上失效

### ISSUE THREAD

**Issue by zz1985summer** [sindresorhus/screenfull.js#181]
chrome 版本 PC 84和85
screenfull.js 试过了5.0.0 和 5.0.2 无效也不报错，只是提示浏览器不支持。
切换回4.2.0就可以正常工作了

**Comment by sindresorhus** [comment]
English-only.

Make sure you read the release notes: https://github.com/sindresorhus/screenfull.js/releases/tag/v5.0.0
