### ISSUE TITLE
Exiting fullscreen in portrait on a range of android devices does not show the address bar.

### ISSUE THREAD

**Issue by JacquesRamsdenGit** [sindresorhus/screenfull.js#215]
Steps to replicate

1. Launch the demo page [here](https://sindresorhus.com/screenfull/ ) in portrait.
2. Go to fullscreen.
3. Exit fullscreen. 

Note that the address bar is not shown when in portrait.

I have attached a video of this being replicated (on a huawei P30)

I have confirmed this happens on at least the following devices, there could be other devices with the same issue.
- Huawei P30
- Samsumg S10
- Samsumg S20

https://user-images.githubusercontent.com/25792830/184618759-bc15db1e-8ff6-4d5a-a653-f25062e0dce4.mp4

**Comment by sindresorhus** [comment]
> Simple wrapper for cross-browser usage of the JavaScript [Fullscreen API](https://developer.mozilla.org/en/DOM/Using_full-screen_mode), which lets you bring the page or any element into fullscreen. Smoothens out the browser implementation differences, so you don't have to.

This package does not actually handle the fullscreening. It's the browser handling that. There's nothing this package can do about the behavior.
