### ISSUE TITLE
Getting 'Module parse failed' error

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [sindresorhus/screenfull.js#217]
Installed the screenfull package but getting the error:

<img width="533" alt="Screenshot 2022-10-18 at 5 21 40 PM" src="https://user-images.githubusercontent.com/82080446/196422106-af2ace86-2225-44b0-9f5e-f4c95b8b5532.png">

**Comment by sindresorhus** [comment]
This is a problem with your bundler, not this package.
