### ISSUE TITLE
Deprecate onchange/onerror?

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/screenfull.js#63]
Initially had an idea to add an `unbind` method to remove all event handlers that screenfull creates and send a patch, but would much rather just clean up my own events that I registered through `addEventListener`. Would be happy to submit a patch removing these handlers if you're OK with it. :+1:

**Comment by naheller** [comment]
@ben-eb I'm still seeing `onchange` listed in the [readme](https://github.com/sindresorhus/screenfull.js#onchangefunction). Is this a mistake?

**Comment by ben-eb** [comment]
The API was changed after this patch was landed, I don't know when. It's been over 4 years since. :wink:

**Comment by sindresorhus** [comment]
Seems it was added back again in https://github.com/sindresorhus/screenfull.js/pull/98 `¯\_(ツ)_/¯`
