### ISSUE TITLE
Chrome - Chromcast tab 

### ISSUE THREAD

**Issue by bboerendans** [sindresorhus/screenfull.js#70]
When i'm casting a tab in Chrome with Chromecast (with Google Cast extension) and use this script to make it fullscreen, it makes it just smaller, like 640*480. With the keyboard button (F11) it's working fine.

When I don't cast it to my Chromecast, fullscreen with the script is working fine. So I don't know if this could be solved, but maybe someone has an idea how to solve this?

**Comment by sindresorhus** [comment]
Sounds like a bug with Chrome. This plugin just wraps the native APIs so not much I can do about it.

Make sure you're fullscreening the document though, and not an element. You could also try setting the body/html width/height to 100%.

Might also want to open a Chrome bug ticket (though make sure to include a reproducible test case):
https://code.google.com/p/chromium/issues/list
