### ISSUE TITLE
gh-pages forcing HTTP

### ISSUE THREAD

**Issue by belm0** [sindresorhus/screenfull.js#72]
It would be nice if the gh-pages URL's for this project didn't redirect to sindresorhus.com (forcing HTTP), so that apps could use the script from gh-pages directly.

I.e. currently https://sindresorhus.github.io/screenfull.js/dist/screenfull.min.js redirects to http://sindresorhus.com/screenfull.js/dist/screenfull.min.js, causing browser to throw cross-scheme exception.

Thanks for considering and for the useful tool.

**Comment by sindresorhus** [comment]
That's intentional. You absolutely shouldn't directly link that. GitHub has hotlink limits. Rather use the referenced CDN link if you want to directly link to the script ;)
