### ISSUE TITLE
Full Screen API doesn't work in object tag and frameset

### ISSUE THREAD

**Issue by znnz** [sindresorhus/screenfull.js#74]
#### It's work in firefox but not in Chrome and others browser. I know that it's work on iFrame. Please clarify my problem. Thanks
![2015-03-19_1818](https://cloud.githubusercontent.com/assets/6309215/6728362/590a033a-ce64-11e4-80f1-a96f8cb916fb.png)

**Comment by kevva** [comment]
https://github.com/sindresorhus/screenfull.js#documentation

**Comment by sindresorhus** [comment]
Use StackOverflow for support questions: http://stackoverflow.com/questions/ask
