### ISSUE TITLE
Manual fullscreen doesn't trigger event

### ISSUE THREAD

**Issue by ThomasPerraudin** [sindresorhus/screenfull.js#82]
Hello, thank you for this awesome API wrapper.

I have a problem when I set the fullscreen manually (typing F11): the event on fullscreenchange is not triggered. (Chrome 43)
```javascript
    document.addEventListener(screenfull.raw.fullscreenchange, function () {
        //never executed when typing F11
        console.log('Am I fullscreen? ' + (screenfull.isFullscreen ? 'Yes' : 'No'));
    });
```

**Comment by sindresorhus** [comment]
That's how the native API works. This is just a small wrapper. Nothing I can do anything about.

**Comment by ThomasPerraudin** [comment]
Thanks, I thought it was the way your wrapper worked.
