### ISSUE TITLE
Textarea is not editable in Safari

### ISSUE THREAD

**Issue by CezarLuiz0** [sindresorhus/screenfull.js#84]
When I request fullscreen, my textarea in Safari doesn't work, don't allow type in keyboard. I receive a sound feedback from browser like "block".

Why?

See: http://stackoverflow.com/questions/12274356/why-is-textarea-not-editable-in-fullscreen-mode

Thanks

**Comment by sindresorhus** [comment]
From the readme:

> Safari doesn't support use of the keyboard in fullscreen.

**Comment by CezarLuiz0** [comment]
Sorry.

Thanks!
