### ISSUE TITLE
Fullscreen active class

### ISSUE THREAD

**Issue by halibegic** [sindresorhus/screenfull.js#88]
Hi, first of all great plugin :+1: 

I'm trying to add CSS class on document body when full screen is active, example:
```javascript
if(!screenfull.isFullscreen) {

      screenfull.request(el);
      
      $('body').addClass('fullscreen-active');
} else {

      screenfull.exit();

      $('body').removeClass('fullscreen-active');
}
```
This works great, but when the element is in the full screen and I pressed ESC key or return on mobile device class is not removed. Any tip how to solved it?

Thank you

**Comment by sindresorhus** [comment]
You need to listen to the [`fullscreenchange` event](https://github.com/sindresorhus/screenfull.js#raw). Your issue is just JS, though. Nothing specifically to do with this module.
